version: '3.1'

services:
  
  db-auth:
    image: postgres
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    volumes:
      - db-auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  db-vehicle:
    image: postgres
    environment:
      POSTGRES_USER: vehicle
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vehicle
    volumes:
      - db-vehicle:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  db-report:
    image: postgres
    environment:
      POSTGRES_USER: report
      POSTGRES_PASSWORD: root
      POSTGRES_DB: report
    volumes:
      - db-report:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - mynetwork

  api:
    build: ./backend
    ports:
      - "9001:9001"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - api
  
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - "rabbit:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db-auth:
  db-vehicle:
  db-report:
  rabbit:
