version: '3'
services:
  db-auth:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    ports:
      - "9001:9001"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - "rabbit:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456

networks:
  mynetwork:

volumes:
  db-data:
  rabbit:
